### ISSUE TITLE
[Bug] <tiktok_ads__ad_report grouping by JSON>

### ISSUE THREAD

**Issue by lsusie** [fivetran/dbt_tiktok_ads_source#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Posted about in the dbt #tools-fivetran Slack. Thread here: https://getdbt.slack.com/archives/C01D1R2JLLA/p1683222999447559

When running the ad_reporting package I'm getting this error in `tiktok_ads__ad_report`. One the most recent version of the package ([">=1.3.0", "<1.4.0"])

```
17:32:49  BigQuery adapter: Retry attempt 1 of 1 after error: BadRequest('Grouping by expressions of type JSON is not allowed at [101:38]')
```

When digging a bit deeper it looks like 4 columns (`age`, `languages`, `actions_categories`, `interest_category`) are coming in a JSON array from the source model `tiktok_ads.adgroup_history` which is causing the `group by` to not work and cause the error above.

![Screenshot 2023-05-04 at 3 49 09 PM](https://user-images.githubusercontent.com/100633490/236349847-280d70a4-f0b2-4f19-8ff5-60c244310784.png)

Dug into a bit with Joe Markiewicz on Slack and suggested to raise it as an issue

> That's really interesting and I haven't seen this issue before, thanks so much for sharing! I would recommend opening an issue on the tiktok_ads_source package so my team can take a closer look and consider possibly removing these fields from the staging package. So they don't causes an error like this.

### Relevant error log or model output

```shell
17:32:49  BigQuery adapter: Retry attempt 1 of 1 after error: BadRequest('Grouping by expressions of type JSON is not allowed at [101:38]')
```

### Expected behavior

I expected the model to complete the full run and materialize the end `ad_reporting__ad_report` report. 

### dbt Project configurations

version: '1.3.0'
require-dbt-version: ">=1.3.0"
config-version: 2

No pass through columns and using tiktok, Microsoft, Facebook, Twitter, and Google as platforms.

### Package versions

([">=1.3.0", "<1.4.0"])

### What database are you using dbt with?

bigquery

### dbt Version

version: '1.3.0'

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @lsusie thanks for opening this issue!

It looks that these fields are in fact being populated as type JSON which is causing the downstream grouping to error out. I believe an easy fix could be removing these fields from the grouping to ensure there is no error down the line. That being said, do you feel these fields are critical to gaining value from these models? If not, we should be able to remove them!

Let me know your thoughts!

**Comment by lsusie** [comment]
Hey @fivetran-joemarkiewicz !

Currently most of those fields are an empty json array so removing them it wouldn't impact the value of the reports for us!

**Comment by fivetran-avinash** [comment]
Hi @lsusie !  We believe we have deployed a fix that should have resolve any issues you might have with this package. Let us know how the new release works for you!

**Comment by lsusie** [comment]
@fivetran-avinash Just updated the package and everything ran perfectly! Thanks for the fix on this!
